### ISSUE TITLE
Get Unknown model with "DeviceHardware.Version Ex: Sysctlbyname" 

### ISSUE THREAD

**Issue by jinnan** [dannycabrera/Get-iOS-Model#10]
Hi, 
I've downloaded the package from NuGet in my iOS project of a "Xamarin-PCL structure project".

I've tried to get Model of my iPad but I keep getting "DeviceHardware.Version Ex: Sysctlbyname" exception and the returned value is "Unknown".
Please help !

**Comment by dannycabrera** [comment]
Hi @jinnan, what iPad do you have and could you please give the model # on the back of your iPad. Should be something like A1432 (this is for my iPad mini). Thanks

**Comment by jinnan** [comment]
hi @dannycabrera I've tested on 2 iPads, their Model# are : A1474 and A1566

**Comment by dannycabrera** [comment]
@jinnan what iOS version are you running?

**Comment by jinnan** [comment]
@dannycabrera iOS 10.3.3 for A1566 and iOS 9.3.5 for A1474

**Comment by jinnan** [comment]
@dannycabrera I juste tested on my iPhone6S (iOS 10.3.3), it doesn't work neither, I got the same exception.

**Comment by dannycabrera** [comment]
@jinnan likely related to the type (Xamarin-PCL structure project) of project. sysctlbyname is failing. Will check into it.

**Comment by jinnan** [comment]
@dannycabrera Ok, I'll wait for your good news, thank you :)

**Comment by jimbobbennett** [comment]
I've just tried it out by calling the NuGet from an iOS app and it works. You shouldn't be able to add this package to a PCL, so maybe we ned to change the NuGet to only install into Xamarin.iOS projects?

**Comment by dannycabrera** [comment]
@jimbobbennett agree, not sure this belongs in a PCL. Still new to creating nuget packages so do you know what needs to change to only allow Xamarin.iOS projects? Thanks

Also, already have the iPhone 8, 8 Plus and X ready to go, just waiting on the hardware strings.

**Comment by jinnan** [comment]
hi @jimbobbennett 
I haven't try it in a single iOS project, but I believe it works well. In my PCL structure, the package is only available for iOS project, so I just added it to my iOS project. I added an abstract class in PCL project so I can call the funcrion from PCL. Also, I tried to call it directly in delegate page of iOS project during the initialization, and I got same  exception. 
I'll try it in a new PCL project later, there should be something different between single iOS project and PCL structure project.

**Comment by jinnan** [comment]
Hi again @dannycabrera @jimbobbennett 

I created a new PCL structure project and a new project iOS, resp. None of them worked with the package....

In detail: 
- In Visual Studio Community for Mac, File-> New Solution... -> iOS App -> Single View App

**Comment by dannycabrera** [comment]
@jinnan was able to replicate issue on Single View App. Have an idea on what it could be so let me test out a few things. Keep you posted.

**Comment by dannycabrera** [comment]
@jinnan I pushed package v1.1 to nuget and should get indexed here in a bit so be on the lookout. Let me know if that works.

**Comment by jinnan** [comment]
Bravo ! It works!! Good job, thanks a lot 👍👍👍  @dannycabrera

**Comment by dannycabrera** [comment]
Weird issue, all I did was rebuild package and that did the trick. Glad it works now and thanks for reporting it.
