### ISSUE TITLE
Not able to detect the simulator model version

### ISSUE THREAD

**Issue by vhugogarcia** [dannycabrera/Get-iOS-Model#11]
Hello,

When running the application on the simulator I get wrong values such as:

Xamarin.iOS.DeviceHardware.Version => x64
Xamarin.iOS.DeviceHardware.Model => Simulator

However, we don't have all physical phones for testing so we use the simulators. Is it possible to return on simulators the model used for testing? For example: "iPhone X, Simulator" appending the word simulator at the end of it? only when simulator or something different.

Thanks in advance for the amazing work,
Victor

**Comment by dannycabrera** [comment]
Hi @vhugogarcia the problem is that it doesn't return a hardware string (ex. iPad6,12) to identify the model, we instead get i386 or x86_64 in return. Will check into what else can be done to identify it. Good suggestion by the way.

**Comment by vhugogarcia** [comment]
Thanks @dannycabrera That would be really helpful for us developers. 

Thanks again for your work on this library it is really good.

**Comment by russbishop** [comment]
You can query for `ProcessInfo().environment["SIMULATOR_MODEL_IDENTIFIER"]`. The model identifiers match the ones returned by hardware, eg iPhone X is `iPhone10,3`.

**Comment by dannycabrera** [comment]
Huge thanks @russbishop, will get that added here shortly.

**Comment by dannycabrera** [comment]
Thanks everyone. Code change applied version bumped to 1.3 and pushed to Nuget.
