### ISSUE TITLE
Apple store App reject reading via Marshal the hw.machine property (?)

### ISSUE THREAD

**Issue by deczaloth** [dannycabrera/Get-iOS-Model#12]
Hi Dany,

(First of all, sorry if this is not the best way to ask this question, but i am quite new to GitHub :/ )
I am glad i found your package (got the [reference from @LandLu in Xamarin Forums](https://forums.xamarin.com/discussion/comment/346711#Comment_346711) 👍 ). 

Now, i came across this way of obtaining the **iOS model** before in [another thread of **Xamarin Forums**](https://forums.xamarin.com/discussion/comment/312571/#Comment_312571), where @JohnHardman shares code from **XLabs**. There, the user who asks the question draws attention over the fact that "_reading via Marshal the hw.machine property ... could be interfere with the Apple Guidelines because you use not free to use SDK abilities. This could result in a permanent suspension of your account._"

Could you share what you know about this and if it is secure to use your library/code in my App?

Thanks,

Julipan

**Comment by dannycabrera** [comment]
Hi @deczaloth,

It shouldn't be a problem as Apple checks every app upon submission to see what API calls are made and retrieving the hardware string hasn't been a violation. There are other calls I have seen rejected but not hw.machine. Hope that answers your concern. Regards
