### ISSUE TITLE
Unable to install Nuget package version 1.11.0

### ISSUE THREAD

**Issue by kevingy** [dannycabrera/Get-iOS-Model#19]
I am unable to add the 1.11.0 Nuget package to my .NET Framework 4.7 project. I'm getting the following error:

```
Install-Package : Failed to add reference. The package 'dannycabrera.GetiOSModel' tried to add a framework reference to 
'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package 
owners for assistance.
  Reference unavailable.
```

I tried installing System.Drawing.Common manually, but I'm still getting the same error.

It is also worth noting that I **can** install 1.10.0. That version does throw this error.

**Comment by dannycabrera** [comment]
Hi @kevingy been looking into this to see what .net framework assembly or process is packaging System.Drawing.Common.dll in there as it's not referenced in my code. If anything will upload new version manually removing it to resolve the error. Let you know in a bit.

**Comment by dannycabrera** [comment]
@kevingy is the email on your profile your preferred contact? Would like to send you an updated nuget package before I upload to see if you could confirm issue is resolved. Thanks

**Comment by kevingy** [comment]
@dannycabrera It is, yes. I'll keep an eye out for the updated package.

**Comment by kevingy** [comment]
@dannycabrera I tested the nuget package you sent. It works perfectly!

**Comment by dannycabrera** [comment]
@kevingy  Awesome, just pushed v1.13.0 to nuget. Might be an hour before it's validated and published.
