### ISSUE TITLE
iPhone SE 2nd Gen hardware string and model name?

### ISSUE THREAD

**Issue by zijianhuang** [dannycabrera/Get-iOS-Model#20]
I know it was announced on 15th of April is still in pre-order stage. Is it possible to get its hardware string and update iOSHardware.cs?

**Comment by dannycabrera** [comment]
Hello @zijianhuang I have the new hardware strings ready to go but I waiting on Apple to release the info so I can confirm them. Should have a nuget package ready in the next couple days.

**Comment by dannycabrera** [comment]
Library was updated and submitted nuget package v1.15.
