### ISSUE TITLE
Proposal: JSON meta for lookup

### ISSUE THREAD

**Issue by zijianhuang** [dannycabrera/Get-iOS-Model#22]
Currently everytime Apple releases a new iPhone/iPad model, you have to update the C# codes and make a package release.

It may be more flexible and less overhead to store the mappings in a JSON file which will be loaded into a Dictionary structure.

Actually, in `iOSChipTypeMap.cs` you already have a Dictionary for mapping hardware ID to chip type.

The proposed JSON structure is like:
```js
{
  "iPad11,3": {
    "chip": "A10Fusion",
    "model": ""iPad Air 3 Wi-Fi",
  },
  
  "iPad11,4": {
...
  }
}
```
The JSON file is by default staying with the package assembly which will load the JSON file in this location.

So in the future when new iPhone/iPad model comes out, the application developers just needs to update the JSON file.

Aftermath of such change:
And through such allocation of meta data, you may even create a simple Web service that provides the mappings. And an iOS app may locate the mappings in the local JSON file. If not found, then the app talks to the Web service to find the latest mappings. So app developers don't have to build and release everytime a new iPhone/iPad model comes out.

If you accept this proposal, you may assign to one of the existing contributors, or I can fork and raise a pull request later.

**Comment by zijianhuang** [comment]
Done at https://github.com/zijianhuang/Get-iOS-Model.

## Changes in Fork

1. Simplify code structure, with DeviceInfo.json replacing if-ten and dictionary, so updating the mapping will be just updating the JSON file while the programming interfaces remain the same to Xamarin App developers.
2. The mapping could be used in a lookup Web service in addition to iOS app.
3. An iOS app may check the bundled ModelInfo.json. And if no match found, check the Web service which may be updated more often than the app.

**Comment by dannycabrera** [comment]
Thanks for the proposed option @zijianhuang however, I never implemented such feature so that this library does not require any sort of connectivity.
