### ISSUE TITLE
ChipType not visible

### ISSUE THREAD

**Issue by fullphat** [dannycabrera/Get-iOS-Model#23]
`ChipType` is marked as private in the latest (and other previous) version of the NuGet package, so this example given in the readme doesn't work:

`Console.WriteLine(Xamarin.iOS.DeviceHardware.ChipType);`

Or have I misunderstood something here? 

Thanks!

**Comment by dannycabrera** [comment]
@fullphat thank you for pointing that out. This should now be fixed in nuget package v1.16 I just submitted.
