### ISSUE TITLE
Values in iOS App not matching samples

### ISSUE THREAD

**Issue by luis-cortina** [dannycabrera/Get-iOS-Model#24]
![image](https://user-images.githubusercontent.com/25346332/95547379-1f64c280-09c0-11eb-8ede-4f51fdbe077c.png)

Any idea why this is not displaying as the examples in the main page?

Luis

**Comment by dannycabrera** [comment]
@luis-cortina it appears you running this in a simulator, is that correct? If so that is expected. Only when running on a physical device will a valid iPhoneX,X hardware string be returned as well as a model number. Let me know.

**Comment by dannycabrera** [comment]
@luis-cortina awesome.
