### ISSUE TITLE
iPhone 7 & iPhone 7 Plus Hardware Strings

### ISSUE THREAD

**Issue by adamzucchi** [dannycabrera/Get-iOS-Model#5]
First, thank you so much for creating and supporting this library!  :)

Do we have any clues as to what the iPhone 7 and iPhone 7 Plus hardware strings will be?  

Or do we need to wait until the official launch of the phones on 9/16/16?

**Comment by dannycabrera** [comment]
Was planning on updating it today. Apple released the iPhone 7 tech specs already so will get it done.

**Comment by dannycabrera** [comment]
Thanks for the reminder @adamzucchi, just pushed out an update.

**Comment by adamzucchi** [comment]
@dannycabrera Thanks for the quick update!
