### ISSUE TITLE
Any plans for a NuGet?

### ISSUE THREAD

**Issue by jimbobbennett** [dannycabrera/Get-iOS-Model#6]
As title really - any plans for a NuGet package?

**Comment by dannycabrera** [comment]
Had not thought about it but will definitely look into it.

**Comment by jimbobbennett** [comment]
PR raised for this - https://github.com/dannycabrera/Get-iOS-Model/pull/7

**Comment by dannycabrera** [comment]
Thanks @jimbobbennett will check it out today

**Comment by SeeD-Seifer** [comment]
I would use that!

**Comment by jimbobbennett** [comment]
@dannycabrera - thanks for merging the PR. Are you going to push to nuget, or do you want me to do it?

**Comment by dannycabrera** [comment]
@jimbobbennett been trying to create the package on VS2017 from PC and msbuild having issues with it appears is this line "<Import Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.CSharp.targets" />". Were you able to create the package?

**Comment by jimbobbennett** [comment]
Do you have the Xamarin workload installed in VS2017? I can create the package fine from VS for Mac. I'll create it and add it as a release to the repo.

**Comment by dannycabrera** [comment]
Thanks for the upload @jimbobbennett. Getting same error from VS on Mac:

<img width="887" alt="vsmac" src="https://user-images.githubusercontent.com/1189224/28042282-99c03c12-659a-11e7-9e42-73951d1b5b1f.png">

**Comment by dannycabrera** [comment]
Thanks once again @jimbobbennett. Here ya go @SeeD-Seifer https://www.nuget.org/packages/dannycabrera.GetiOSModel/1.0.0

**Comment by SeeD-Seifer** [comment]
That's awesome! Thanks!

**Comment by jimbobbennett** [comment]
Ah - looks like I moved something and forgot to update the csproj - apologies.

PR raised for the fix:
https://github.com/dannycabrera/Get-iOS-Model/pull/9

**Comment by dannycabrera** [comment]
The pack issue was the issue I had building nuget package, all good now with PR #9
