### ISSUE TITLE
iOSHardware class should be public

### ISSUE THREAD

**Issue by SeeD-Seifer** [dannycabrera/Get-iOS-Model#8]
`iOSHardware` can't be reached using NuGet package

**Comment by jimbobbennett** [comment]
What do you need from that class? There DeviceHardware class now has a Model property that calls `iOSHardware` using the version from `DeviceHardware`

**Comment by SeeD-Seifer** [comment]
Oh man... didn't notice.
In that case would be nice update README.

**Comment by jimbobbennett** [comment]
Good call - will update and raise a PR once the nuget is published

**Comment by jimbobbennett** [comment]
Readme has been updated in 

https://github.com/dannycabrera/Get-iOS-Model/pull/9

I'll update it again to reflect the nuget once it has been published

**Comment by dannycabrera** [comment]
Updated README with nuget info. Thanks guys
